var signone = document.querySelector('#signatureone')
var signaturetwo = document.querySelector('#signaturetwo')
var signaturethree = document.querySelector('#signaturethree')
var answerone = document.querySelector('#answerone')
var answertwo = document.querySelector('#answertwo')
var answerthree = document.querySelector('#answerthree')
var answer = document.querySelectorAll('.answer')
var none = document.querySelector('.none')

signone.addEventListener('click', ()=>{
    answerthree.classList.add('none')
    answertwo.classList.add('none')
    answerone.classList.toggle('none')
    signone.setAttribute('class','fa-solid plussign fa-minus')
    signaturetwo.setAttribute('class','fa-solid plussign fa-plus')
    signaturethree.setAttribute('class','fa-solid plussign fa-plus')
})
signaturetwo.addEventListener('click', ()=>{
    answerthree.classList.add('none')
    answerone.classList.add('none')
    answertwo.classList.toggle('none')
    signaturetwo.setAttribute('class','fa-solid plussign fa-minus')
    signaturethree.setAttribute('class','fa-solid plussign fa-plus')
    signone.setAttribute('class','fa-solid plussign fa-plus')
})
signaturethree.addEventListener('click', ()=>{
    answerone.classList.add('none')
    answertwo.classList.add('none')
    answerthree.classList.toggle('none')
    signaturethree.setAttribute('class','fa-solid plussign fa-minus')
    signaturetwo.setAttribute('class','fa-solid plussign fa-plus')
    signone.setAttribute('class','fa-solid plussign fa-plus')
})